#
# Make sure the Raspberry Pi user is disabled (TODO: wipe it out completely)
#
- name: Disable Raspberry Pi user
  user: name=pi shell=/bin/false password=locked
- name: Remove group memberships
  user: name=pi group=pi groups=pi append=no
#- name: "Kill all processes belonging to 'pi'"
#  command: pkill -u pi
#- name: Remove default Raspberry Pi user
#  user: name=pi state=absent remove=yes
#- name: Remove Raspberry Pi group
#  user: group=pi state=absent remove=yes
#- name: Remove old pi home directory
#  file: path=/home/pi recurse=yes

#
# Configure the "tim" user
#
- name: "Setup user 'tim' (Groups)"
  user: "name=tim append=yes groups={{ item }}"
  with_items:
    - adm
    - audio
    - cdrom
    - dialout
    - games
    - gpio
    - i2c
    - input
    - netdev
    - plugdev
    - spi
    - sudo
    - users
    - video

#
# Add a user for network shares
#
- name: "Setup networking user"
  user: name="{{ NETWORK_USERNAME }}" state=present password="{{ NETWORK_PASSWORD }}"
