#
# Configure basic system settings
#

- copy: dest=/etc/sysctl.conf src=files/etc/sysctl.conf

# todo: set the hostname

# Make sure that LightDM doesn't autologin anyone
- name: Disable LightDM auto-login
  replace: dest=/etc/lightdm/lightdm.conf regexp='^(autologin-user.*)$' replace='#\1'
- name: Restart LightDM
  command: sudo service lightdm restart
