- name: Install necessary utilities
  apt: "name={{ item }}"
  with_items:
    - locate
    - nmap
    - screen
    - vim

- name: Install top-like programs
  apt: "name={{ item }}"
  with_items:
    - htop
    - iotop
