# Packages to be installed in this are based on instructions
# from http://ubuntuforums.org/showthread.php?t=2105755

- name: Install basic necessary packages
  apt: name={{ item }}
  with_items:
    - netatalk
    - libc6-dev
    - avahi-daemon
    - libnss-mdns

