---

- hosts: timmachines
  sudo: yes
  vars_files:
    - "../ansible/machines/{{ HOSTNAME }}.yml"
  tasks:
    - include: tasks/configure-system.yml
    - include: tasks/configure-users.yml
    - include: tasks/configure-networking.yml
